#!/usr/bin/env bash
# Ingestion's approved denylist -> Squid, the enforcement half of the loop.
#
#   sync-denylist.sh            # sync once
#   sync-denylist.sh --watch    # keep syncing every SYNC_INTERVAL seconds
#
# Architecture §7 "MVP enforcement": a file of approved denied domains, plus a
# worker that "safely validates and reloads Squid". Only destinations a human
# approved ever reach /v1/rules.txt, so this worker never decides anything — it
# transports a decision that was already made.
#
# Why the file and not the external_acl helper (§7 "Eventual"): the ubuntu/squid
# image has no python3, curl or wget, so infra/gb10/squid/check-policy cannot
# run inside the container without building a custom image. The file path needs
# nothing in the container at all.
set -euo pipefail

INGESTION="${INGESTION_URL:-http://127.0.0.1:8100}"
DENYLIST_DIR="${DENYLIST_DIR:-/home/dell/vllm/squid/denylist}"
CONTAINER="${SQUID_CONTAINER:-hack-squid}"
SYNC_INTERVAL="${SYNC_INTERVAL:-10}"

# A hostname and nothing else. This file becomes Squid configuration, so an
# unvalidated line is a config-injection primitive — refuse anything that is
# not a plain domain rather than trying to sanitise it.
VALID='^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$'

sync_once() {
    local raw domains=() line
    if ! raw=$(curl -fsS --max-time 10 "$INGESTION/v1/rules.txt" 2>/dev/null); then
        echo "sync-denylist: ingestion unreachable at $INGESTION; leaving the current denylist in place" >&2
        return 1
    fi

    while IFS= read -r line; do
        line="${line%%[[:space:]]*}"
        [[ -z $line ]] && continue
        if [[ $line =~ $VALID ]]; then
            # ONLY the dotted form. In squid, `.host` matches the domain AND
            # all its subdomains, so an exfil path that moves to up.evil.test
            # needs no second approval. Listing both `host` and `.host` is a
            # FATAL config error — squid rejects the second as a subdomain of
            # the first and aborts the reconfigure.
            domains+=(".$line")
        else
            echo "sync-denylist: refusing malformed entry: $line" >&2
        fi
    done <<<"$raw"

    mkdir -p "$DENYLIST_DIR"
    local target="$DENYLIST_DIR/domains.txt" tmp="$DENYLIST_DIR/.domains.tmp"
    {
        echo "# Generated by sync-denylist.sh from $INGESTION/v1/rules.txt"
        echo "# Every entry here was approved by a human. Do not hand-edit."
        printf '%s\n' "${domains[@]+"${domains[@]}"}"
    } >"$tmp"

    if [[ -f $target ]] && cmp -s "$tmp" "$target"; then
        rm -f "$tmp"
        return 0
    fi

    mv "$tmp" "$target"
    local count=${#domains[@]}
    echo "sync-denylist: $count destination(s) denied; reloading squid"
    # reconfigure, not restart: verified to reload without dropping the proxy,
    # so in-flight sessions survive an approval.
    docker exec "$CONTAINER" squid -k reconfigure
}

if [[ ${1:-} == "--watch" ]]; then
    while true; do
        sync_once || true
        sleep "$SYNC_INTERVAL"
    done
else
    sync_once
fi
